### ISSUE TITLE
False positives in kselftests-rtc (arm64 - kevin)

### ISSUE THREAD

**Issue by r-c-n** [kernelci/test-definitions#18]
Seen in some builds but not all. At least in stable-rc/linux-4.19.y: https://linux.kernelci.org/test/plan/id/637dd59d221061bf322abd0b/

Saved log:
[kselftest-rtc-rk3399-gru-kevin.html.gz](https://github.com/kernelci/test-definitions/files/10121508/kselftest-rtc-rk3399-gru-kevin.html.gz)

The job definition yaml is missing a few important parameters:
Example: https://lava.collabora.dev/scheduler/job/7971458

in job definition:

```
- from: git
  name: kselftest-rtc
  parameters:
    BOARD: rk3399-gru-kevin
    BRANCH: stable-rc
    SKIPFILE: skipfile-lkft.yaml
    TESTPROG_URL: None
    TST_CASENAME: null
    TST_CMDFILES: rtc
  path: automated/linux/kselftest/kselftest.yaml
  repository: https://github.com/kernelci/test-definitions.git
  revision: kernelci.org
```

`TESTPROG_URL` and `TST_CASENAME` aren't getting filled, but I don't know who is supposed to fill in the `kselftests_url` and `kselftest_tests` parameters in the job template: https://github.com/kernelci/kernelci-core/blob/main/config/lava/kselftest/kselftest.jinja2

Anyway, this doesn't sit well with the https://github.com/kernelci/test-definitions/blob/main/automated/linux/kselftest/kselftest.sh script. The script will use a default URL if no URL is supplied (https://github.com/kernelci/test-definitions/blob/2ce1f656ee9280c0fedb9c78885a9aa455927dd7/automated/linux/kselftest/kselftest.sh#L110) but here it's getting "None" instead, so the actual kselftests aren't even downloaded or run (https://lava.collabora.dev/scheduler/job/7971458#L1802)

I don't know why LAVA considers this a success, though.
